Fail silently if KUBELET_DRAIN_FAIL_SILENTLY is set
[#156658555]

Signed-off-by: Alton Fong <altonf@vmware.com>

diff --git a/jobs/kubelet/templates/bin/drain.erb b/jobs/kubelet/templates/bin/drain.erb
--- a/jobs/kubelet/templates/bin/drain.erb
+++ b/jobs/kubelet/templates/bin/drain.erb
@@ -17,9 +17,8 @@ main() {
   send_process_stderr_to_logfile_and_syslog
   check_if_pidfile_exists
   check_if_pid_is_running
-
-  fail_if_master_is_running drain_kubelet
-  fail_if_master_is_running delete_drained_node
+  fail_if_not_silent drain_kubelet
+  fail_if_not_silent delete_drained_node
 }
 
 ensure_safe_exit() {
@@ -53,35 +52,18 @@ check_if_pid_is_running() {
   fi
 }
 
-fail_if_master_is_running() {
+fail_if_not_silent() {
   local func=$1
+  local fail_silently=${KUBELET_DRAIN_FAIL_SILENTLY:-<%= p('drain-fail-silently') %>}
 
   if ! $func; then
-    if master_is_running?; then
-      echo 'Master seems to be running and the drain failed!'
-      exit 1
+    if fail_silently; then
+      echo 'Drain step failed silently'
     else
-      echo 'Master seems to be down'
-      echo 'Assuming this is a bosh delete-deployment, the drain failure will be ignored.'
+      echo 'Drain step failed!'
+      exit 1
     fi
   fi
-}
-
-master_is_running?() {
-  local ATTEMPTS_REMAINING=100
-  local cacert=/var/vcap/jobs/kubelet/config/ca.pem
-  local auth_header='Authorization: Bearer <%= p("drain-api-token")  %>'
-
-  while [[ "$ATTEMPTS_REMAINING" -ne 0 ]]; do
-    if curl -sS https://master.cfcr.internal:8443/healthz -H "$auth_header" --fail --cacert "$cacert" --connect-timeout 2 > /dev/null; then
-      return 0
-    else
-      ATTEMPTS_REMAINING=$(( ATTEMPTS_REMAINING - 1 ))
-      sleep 1
-    fi
-  done
-
-  return 1
 }
 
 pid_is_running?() {
