Handle bosh delete-deployment in kubelet drain
When deleting deployment, bosh calls drain on all instances at once,
this causes kube-apiserver to die before kubelet drain happens. There is
no way as of now to figure out if drain is called while deleting
deployment.

As a workaround drain tries 100 times to reach master after kubectl
drain fails to make sure master is not really up. If master responds
within that time, drain fails, otherwise it is assumed that master is
dead as a result of `bosh delete-deployment`

[#155218338]

diff --git a/jobs/kubelet/templates/bin/drain.erb b/jobs/kubelet/templates/bin/drain.erb
--- a/jobs/kubelet/templates/bin/drain.erb
+++ b/jobs/kubelet/templates/bin/drain.erb
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# vi: ft=sh
 
 [ -z "$DEBUG" ] || set -x
 
@@ -16,7 +17,9 @@ main() {
   send_process_stderr_to_logfile_and_syslog
   check_if_pidfile_exists
   check_if_pid_is_running
-  drain_kubelet
+  if ! drain_kubelet; then
+    fail_if_master_is_running
+  fi
 }
 
 ensure_safe_exit() {
@@ -48,6 +51,25 @@ check_if_pid_is_running() {
     echo "$(date) -- Process from pidfile not running, so not attempting to drain."
     exit_with_code 0
   fi
+}
+
+fail_if_master_is_running() {
+  local ATTEMPTS_REMAINING=100
+  local cacert=/var/vcap/jobs/kubelet/config/ca.pem
+  local auth_header='Authorization: Bearer <%= p("drain-api-token")  %>'
+  while true; do
+    if curl -sS https://master.cfcr.internal:8443/healthz -H "$auth_header" --fail --cacert "$cacert" --connect-timeout 2 > /dev/null; then
+      exit 1
+    else
+      ATTEMPTS_REMAINING=$(( ATTEMPTS_REMAINING - 1 ))
+      if [[ "$ATTEMPTS_REMAINING" -eq 0 ]]; then
+        echo 'Master seems to be down'
+        echo 'Assuming this is a bosh delete-deployment, the drain failure will be ignored.'
+        exit
+      fi
+      sleep 1
+    fi
+  done
 }
 
 pid_is_running?() {
