verify system specs are running as part of post-deploy
As part of the post deploy script assert that we've deployed the correct number of pods and that all of them are in the 'Ready' state. This means failure to start system specs (eg, a Dashboard or KubeDNS) will make the deployment as a failure.

This should make it harder to mask issues in system spec failures.

[#141118027]

diff --git a/jobs/kubernetes-system-specs/templates/bin/post-deploy b/jobs/kubernetes-system-specs/templates/bin/post-deploy
--- a/jobs/kubernetes-system-specs/templates/bin/post-deploy
+++ b/jobs/kubernetes-system-specs/templates/bin/post-deploy
@@ -3,6 +3,8 @@
 spec_dir="/var/vcap/jobs/kubernetes-system-specs/config/"
 kubectl="/var/vcap/packages/kubernetes/bin/kubectl --kubeconfig=/var/vcap/jobs/kubeconfig/config/kubeconfig"
 
+TIMEOUT=120
+
 apply_spec() {
   local spec="$1"
   ${kubectl} apply -f "${spec_dir}/${spec}" || echo "${spec} was already deployed"
@@ -16,8 +18,19 @@ deploy_specs() {
   apply_spec "kubernetes-dashboard.yml"
 }
 
+verify_specs() {
+  if timeout "$TIMEOUT" /var/vcap/jobs/kubernetes-system-specs/bin/ensure-specs-running
+  then
+    echo "all expected specs are running"
+  else
+    echo "failed to start all system specs after $TIMEOUT"
+    exit 1
+  fi
+}
+
 main() {
   deploy_specs
+  verify_specs
 }
 
 main
