Adds 2 minute timeout for kubernetes-system-spec post start
- the post start applies the rbac policies once the api server becomes
responsive

[#153535114]

Signed-off-by: Travis Hall <thall@vmware.com>

diff --git a/jobs/kubernetes-system-specs/templates/bin/post-start.erb b/jobs/kubernetes-system-specs/templates/bin/post-start.erb
--- a/jobs/kubernetes-system-specs/templates/bin/post-start.erb
+++ b/jobs/kubernetes-system-specs/templates/bin/post-start.erb
@@ -2,17 +2,16 @@
 
 set -e
 
-main() {
-  local spec_dir="/var/vcap/jobs/kubernetes-system-specs/config/"
-  local kubectl="/var/vcap/packages/kubernetes/bin/kubectl --token '<%= p('admin-password') %>'"
-
-  ${kubectl} apply -f "${spec_dir}/rbac_policy.yml"
-}
-
 echo 'Authorization mode is <%= p('authorization-mode') %>'
 <% if p('authorization-mode').downcase == 'rbac' %>
 echo 'Applying the RBAC policy'
-main
+TIMEOUT=120
+if timeout "$TIMEOUT" /var/vcap/jobs/kubernetes-system-specs/bin/apply_rbac; then
+  echo "Applied the RBAC policy"
+else
+  echo "Failed to apply the RBAC policy after $TIMEOUT with exit code $?"
+  exit 1
+fi
 <% else %>
 echo 'Not applying the RBAC policy.'
 <% end %>
